use_frameworks!

platform :ios, '8.0'

target 'CDFirstCategoryKit_Example' do
  pod 'CDFirstCategoryKit', :path => '../'

  target 'CDFirstCategoryKit_Tests' do
    inherit! :search_paths

    
  end
end
